### ISSUE TITLE
Manually set Node and JSCS paths

### ISSUE THREAD

**Issue by varemenos** [TheSavior/SublimeJSCSFormatter#1]
I'm having issues getting Node to be detected by your script, it keeps saying that Node is not in my `$PATH` after I've following your linter installation guide (installed `jscs` globally, removed `nvm` from `oh-my-zsh`'s `.zshrc`, sourced it in `.zshenv`). Which is kinda of weird since running the follow from the sublime console shows that Node is there:

``` bash
>>> import subprocess
>>> subprocess.check_output(["node", "-v"])
v0.10.24
```

Anyway, this issue is about adding a option in the preferences to manually input Node's path (other packages, like the one that utilizes jsbeautifier, do it too).

For the record I'm on ArchLinux (3.18.6-1-ARCH)

**Comment by elicwhite** [comment]
Give it a try now. You should be able to set the node path. You may run into problems with the jscs command not being found though.

**Comment by varemenos** [comment]
> You may run into problems with the jscs command not being found though

Is there a way to tackle that issue then?

``` bash
Using node.js path on 'linux': /home/adonisk/.nvm/v0.10.24/bin/node
error: JSCS could not be found on your path
Traceback (most recent call last):
  File "/opt/sublime_text_3/sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "/home/adonisk/.config/sublime-text-3/Packages/Sublime-JSCS-Formatter/JSCSFormatter.py", line 42, in run
    if len(output) < 1:
TypeError: object of type 'NoneType' has no len()
```

**Comment by elicwhite** [comment]
Yeah, can you tell me the path of your JSCS executable?

**Comment by varemenos** [comment]
I'm not entirely sure but I guess either this: `/home/adonisk/.nvm/v0.10.24/bin/jscs`

**Comment by elicwhite** [comment]
Out of curiosity, do you have the SublimeLinter-JSCS package installed and working? Did you have to do anything custom for that to work?

**Comment by varemenos** [comment]
Nope, I did nothing it was working just fine out of the box.
I guess the answer to the right way of finding the lib paths is in that package.

Btw, after entering the path strings manually in the python script, I was finally able to use the JSCS lib but apparently I had the 1.11.3 version installed so it didn't work (I guess I need 1.12 for `--fix` to be included).

**Comment by elicwhite** [comment]
Alright, I can add settings for jscs_path.

And yeah, we aren't officially releasing this plugin until JSCS 1.12 officially lands.

**Comment by elicwhite** [comment]
Alright, JSCS path is now a setting in the configuration.
