### ISSUE TITLE
modified Plugin setting files should go in the User directory

### ISSUE THREAD

**Issue by varemenos** [TheSavior/SublimeJSCSFormatter#10]
I assume that you are currently using parts of the HTMLPrettify package for the configuration of the plugin and I'd like to inform you that it's not doing it's job properly. The modified settings for SublimeText plugins should go to the User directory, not in the Package's directory and that's before most of the ST3 plugins are not unzipped and installed in the Packages directory but in the Installed Packages one and stored as zipped files.

When someone presses the "modify node path" for example, they will be directed by your plugin to save the configuration file in the path you specified which is located inside the archive file of the Plugin inside Installed Packages directory.

**Comment by elicwhite** [comment]
Thanks for reporting. This is definitely something I need to look into. Same issue as #11
