### ISSUE TITLE
Override settings on project level

### ISSUE THREAD

**Issue by xavhan** [TheSavior/SublimeJSCSFormatter#17]
I tried to edit my project settings JSON file like this to enable autoformat on save only on this specific project but it does not work. 
I think i missed something and i did not write the good identifier... Somebody help me?

_project.sublime-project_

``` javascript
{
  "settings": {
    "jscsformatter_tools": {
      "format_on_save": true
    }
  }
}
```

**Comment by elicwhite** [comment]
I have never specified plugin specific settings like this on a project level. It is surprising that there seems to be no documentation about this online.

If the format you are showing works, perhaps try `"jscs-formatter" : {` instead of `"jscsformatter_tools": {` _shrug_

**Comment by mrjoelkemp** [comment]
The only way I know how to do per-project settings is via an external configuration file (similar to .jscsrc) defined in the project. 

You could parse one's .jscsrc and just look for an extra field to dictate the format_on_save value. That's not a great habit to get into (unless all plugin settings are contained within a `jscsformatter` object). If editor integration spans beyond Sublime Text, this extra setting could be reused.

**Comment by elicwhite** [comment]
Closing as this seems like something related to Sublime and not this package specifically
