### ISSUE TITLE
Can't find node with NVM, ST3, ZSH

### ISSUE THREAD

**Issue by ghost** [TheSavior/SublimeJSCSFormatter#18]
Hi.

I have ST3 latest beta, NVM with node v0.10.36 and zsh(with oh-my-zsh).

My .zshenv file:

```
export NVM_DIR=$HOME/.nvm
source $(brew --prefix nvm)/nvm.sh
```

nvm has alias default set to v0.10.36

`node -v` works from command line

`which node` gives me `/Users/me/.nvm/v0.10.36/bin/node`

I tried to use JSCS without changing any settings. And i tried to hardcode the paths to `~/.nvm/v0.10.36/..`. Still doesn't work.

Oh-my-zsh doesn't have nvm plugin installed.

Don't know what else to try to make it work.

Always same error:

```
Couldn't find Node.js. Make sure it's in your $PATH by running `node -v` in your command-line.
```

And in sublime console:

```
Using node.js path on 'osx': ~/.nvm/v0.10.36/bin/node
Using jscs path on 'osx': ~/.nvm/v0.10.36/bin/jscs
Unexpected error(<class 'Exception'>): Couldn't find Node.js. Make sure it's in your $PATH by running `node -v` in your command-line.
error: Couldn't find Node.js. Make sure it's in your $PATH by running `node -v` in your command-line.
```

Any ideas?

**Comment by mrjoelkemp** [comment]
Not sure it will fix it, but can you try a non aliased (absolute) path to
node? i.e. try the non-tilde form of the path.

**Comment by ghost** [comment]
@mrjoelkemp actually it did work!!! Thanks a bunch!

**Comment by mrjoelkemp** [comment]
Yay. Thanks for reporting. @thesavior, feel free to close.

**Comment by elicwhite** [comment]
@mrjoelkemp, thanks for helping!

**Comment by OliverJAsh** [comment]
Is this any way to get this to place nicely with nvm, without explicitly setting the node path? `.zshenv` does not prevail.

**Comment by mrjoelkemp** [comment]
@OliverJAsh Can you try setting your node path to `. ~/some/path/to/node`? The dot (at least on OSX) should make it work.

**Comment by OliverJAsh** [comment]
@mrjoelkemp I'm using nvm and I don't want to hard core the path to node anywhere, as it may change frequently (that's the purpose of nvm (node version manager)). I presumed it would find it in my $PATH but it doesn't?

**Comment by mrjoelkemp** [comment]
I see. Thanks for clarifying. 

I don't know what the solution is, but happy to brainstorm ideas in hopes that someone with a windows machine would lend a hand and draft a PR.

Setting `SHELL=True`, which we do on Windows should respect the `PATH`.

Perhaps we should try not setting `cwd` on Windows https://github.com/TheSavior/SublimeJSCSFormatter/blob/cd5ab6f84b5412e7604d21b74bbb1c5f9dccd809/JSCS-Formatter.py#L144 since setting `cwd` [makes the executable lookup relative to the set directory](https://github.com/TheSavior/SublimeJSCSFormatter/blob/cd5ab6f84b5412e7604d21b74bbb1c5f9dccd809/JSCS-Formatter.py#L144).

Any other ideas are welcome.

**Comment by OliverJAsh** [comment]
The plugin doesn't seem to be looking for node or jscs in the `$PATH`. It only seems to care about the path options provided: https://github.com/TheSavior/SublimeJSCSFormatter/blob/cd5ab6f84b5412e7604d21b74bbb1c5f9dccd809/JSCS-Formatter.py#L72.

Other Sublime plugins seem to handle this quite fell, for example SublimeLinter: https://github.com/SublimeLinter/SublimeLinter3/blob/ce29335059a0aecf7f8ef8c2b6b5e3b07a70542b/lint/util.py#L1352-1364. The `PATH` is used inside `create_envrionment`.

**Comment by mrjoelkemp** [comment]
@OliverJAsh Haven't forgotten about this issue, but I'm juggling a bunch of other projects. Any chance you'd be able to investigate reusing parts of the SublimeLinter solution to see if it resolves the issue? Any help is appreciated.
