### ISSUE TITLE
ES6 Syntax preventing formatter form running

### ISSUE THREAD

**Issue by matt-e-king** [TheSavior/SublimeJSCSFormatter#20]
Hey there! Thanks for the contribution. I am running Sublime Text 3 on a Mac using the Sublimelinter-jscs, and I am having issues running this formatter plugin on files with ES6 syntax. For instance:

Assume this code has "style" issues:

```
var Module = require('./module');

setInterval(function () {
  if (boolean || anotherBoolean) {

    return;

  }
}, delay);
```

When I run the formatter or save the file, the JSCS Formatter works perfectly. But if I convert that same code to:

```
import Module from 'Module';

setInterval(() => {
  if (boolean || anotherBoolean) {

    return;

  }
}, delay);
```

The JSCS Formatter doesn't appear to be working. I have `--esnext` and `--esprima=esprima-fb` in my Sublimelinter settings, so I still get the Sublimelinter visual indicators.

Lastly, in my Sublime console, when I run JSCS Formatter on the latter, I get only the following lines output:

```
Using node.js path on 'osx': /usr/local/bin/node
Using jscs path on 'osx': /usr/local/bin/jscs
```

Any thoughts? Thanks!

**Comment by elicwhite** [comment]
What happens if you specify esnext and the esprima in your .jscsrc file instead of passing them as args to the jscs executable? http://jscs.info/overview.html#esnext

Also, can you post your settings file for SublimeLinter-JSCS?

**Comment by matt-e-king** [comment]
Putting them directly in my .jscsrc file did the trick! I thought the .jscsrc file was strictly for rules. That helps a lot, I was actually confused as to where to use those "options" were supposed to go. 

Thanks for the quick response!

Here is my SublimeLinter-JSCS file:

```
{
    "user": {
        "debug": true,
        "delay": 0.25,
        "error_color": "D02000",
        "gutter_theme": "Packages/SublimeLinter/gutter-themes/Default/Default.gutter-theme",
        "gutter_theme_excludes": [],
        "lint_mode": "background",
        "linters": {
            "jscs": {
                "@disable": false,
                "args": [
                    "--config=~/.jscsrc",
                    "--esnext",
                    "--esprima=esprima-fb"
                ],
                "excludes": []
            }
        },
        "mark_style": "outline",
        "no_column_highlights_line": false,
        "passive_warnings": false,
        "paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "python_paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "rc_search_limit": 3,
        "shell_timeout": 10,
        "show_errors_on_save": false,
        "show_marks_in_minimap": true,
        "syntax_map": {
            "html (django)": "html",
            "html (rails)": "html",
            "html 5": "html",
            "php": "html",
            "python django": "python"
        },
        "warning_color": "DDB700",
        "wrap_find": true
    }
}
```

**Comment by elicwhite** [comment]
Glad that solved the problem. 

Thanks for sharing your SublimeLinter config. I didn't actually know that you could pass args that way. :P
