### ISSUE TITLE
Explore executable path options for Windows.

### ISSUE THREAD

**Issue by elicwhite** [TheSavior/SublimeJSCSFormatter#21]
There have been some issues with finding and executing node on Windows. Lets try to see if we can find more reasonable defaults.

Referencing #12 and #14

**Comment by elicwhite** [comment]
Resolved by #22

**Comment by steveoh** [comment]
This does not work when you use nvm. The path would be 

`%AppData%\nvm\{version}\node_modules\jscs`

what nvm does is symlink that folder to

`C:\Program Files\nodejs\node_modules`
