### ISSUE TITLE
Trying to figure out a setting

### ISSUE THREAD

**Issue by SomethingSexy** [TheSavior/SublimeJSCSFormatter#27]
I am using the formatter and I can't figure out which jscs property fixes this.

This is how it outputs it when I use the formatter:

``` javascript
  var _assign = require('lodash/object/assign'),
  _merge = require('lodash/object/merge'),
  _isArray = require('lodash/lang/isArray'),
  _map = require('lodash/collection/map');
```

and this is what I want:

``` javascript
  var _assign = require('lodash/object/assign'),
     _merge = require('lodash/object/merge'),
     _isArray = require('lodash/lang/isArray'),
     _map = require('lodash/collection/map');
```

It seems looking at this issue, this hasn't been handled yet via jscs https://github.com/jscs-dev/node-jscs/issues/454

So I am curious what else might be effecting the formatter to do this?

**Comment by SomethingSexy** [comment]
It seems like it is around this setting:

"validateIndentation": 2

Does that make sense that it formats it like that automatically?

**Comment by elicwhite** [comment]
It appears that, as you say, the rule to enforce that style of indentation doesn't exist yet. Once it does, the formatter will respect those rules.

**Comment by mrjoelkemp** [comment]
@TheSavior close?
