### ISSUE TITLE
validateQuoteMarks has no effect

### ISSUE THREAD

**Issue by websirnik** [TheSavior/SublimeJSCSFormatter#29]
When I declare:

``` json
{
    "validateQuoteMarks": "'"
}
```

I expect this:

``` js
var string = "text";
```

To become this:

``` js
var string = 'text';
```

But that is not happening.

**Comment by elicwhite** [comment]
JSCS currently doesn't autoformat quote marks. There is an open PR [here](https://github.com/jscs-dev/node-jscs/pull/1265) with lots of discussion

**Comment by mrjoelkemp** [comment]
@TheSavior close?
