### ISSUE TITLE
Build this into the sublime linter plugin? 

### ISSUE THREAD

**Issue by mrjoelkemp** [TheSavior/SublimeJSCSFormatter#3]
Did we ask if they'd like this feature? 

That plugin already has a following, so it would make sense for everything to be under one roof. 

Thoughts?

**Comment by varemenos** [comment]
But this isn't actually a linter is it? It's formatting the code depending on the `.jscsrc` configuration file

**Comment by mrjoelkemp** [comment]
Autofix is a feature of jscs which is a "linter." I view the sublime linter plugin as the holistic, editor representation of jscs. 

Of course, nothing stops the community from creating separate tooling, but pooling together resources makes maintenance easier. Just something to consider.

**Comment by elicwhite** [comment]
I would love for this to be part of SublimeLinter. There doesn't seem to be any precedent for a SublimeLinter plugin to do any more than lint and return errors and that project doesn't seem to have the infrastructure to support it currently. 

I should at least ask them though. :P

**Comment by elicwhite** [comment]
Issue raised here: https://github.com/SublimeLinter/SublimeLinter3/issues/207

**Comment by mrjoelkemp** [comment]
I think https://github.com/SublimeLinter/SublimeLinter-jscs/issues is the more appropriate repo.

**Comment by elicwhite** [comment]
I decided not to comment there because the repo activity looks dead, and it's more of an infrastructure question than a linter question. I might end up having to ask there as well though.

**Comment by mrjoelkemp** [comment]
@TheSavior No word from them?
