### ISSUE TITLE
Does not show up in Install Package list.

### ISSUE THREAD

**Issue by sarbbottam** [TheSavior/SublimeJSCSFormatter#32]
![screen shot 2015-05-20 at 9 46 25 pm](https://cloud.githubusercontent.com/assets/949380/7741797/b9cfc442-ff39-11e4-96f6-3e34a7c027f2.png)

**Comment by mrjoelkemp** [comment]
1. Try just JSCS and see if it comes up
2. You probably need to clear your package control cache or upgrade package control
3. Restart sublime

**Comment by sarbbottam** [comment]
> > Try just JSCS and see if it comes up

Looks like my package control is messed up, could not list `JSCS` too.

Thanks,

**Comment by mrjoelkemp** [comment]
@TheSavior close please
