### ISSUE TITLE
format all files instead of opened one?

### ISSUE THREAD

**Issue by coodoo** [TheSavior/SublimeJSCSFormatter#34]
Is it possible to hit one key and have all files under the same project folder be formatted? Thanks.

**Comment by mrjoelkemp** [comment]
Hi Jeremy,

Thanks for contributing. This would likely be a one-time use feature. I'm
torn between building that and just deferring users to running jscs autofix
on the directory via the terminal.

What do you think?

**Comment by coodoo** [comment]
Ah, I didn't notice there's this `-x` option in `jscs` to format files while linting, of course it makes more sense to do that via CLI then, thanks for the heads-up!
