### ISSUE TITLE
Add API functionality so we can use options like ES6 

### ISSUE THREAD

**Issue by zellwk** [TheSavior/SublimeJSCSFormatter#35]
Would be great if JSCS formatter can support ES6 since I'm writing with them already :)

**Comment by elicwhite** [comment]
This library doesn't have any impact on the support of JSCS and ES6. JSCS-Formatter uses whatever version of JSCS you have installed. The [JSCS Library](https://github.com/jscs-dev/node-jscs) is adding ES6 support.

**Comment by zellwk** [comment]
Question: How do I add enable the esnext option to automatically format ES6 syntax then? I'm able to get normal ES5 working, but I have no idea where I can enable the `esnext` options.

**Comment by elicwhite** [comment]
The JSCS-Formatter formats files using the same configuration file the jscs cli uses. Specifying `esnext` in that configuration file will enable it for the formatter as well.

**Comment by zellwk** [comment]
Oh I missed it. Thanks for the help! :)
