### ISSUE TITLE
Keybinding?

### ISSUE THREAD

**Issue by astanciu** [TheSavior/SublimeJSCSFormatter#37]
How can I set a custom shortcut key to execute the formatting? Not sure what the 'command' is to put into my settings file.

**Comment by elicwhite** [comment]
If you go to 

```
Sublime Text -> Preferences -> Package Settings -> JSCS Formatter -> Settings - Default
```

You'll see:

```
[{
  "keys": ["super+shift+h"],
  "command": "format_javascript"
}]
```

You should be able to add that with whatever keys you want to `Settings - User` for the package.
