### ISSUE TITLE
JSCSFormatter can't exclude specific files configured in the .jscsrc file.

### ISSUE THREAD

**Issue by Kuznetsov2100** [TheSavior/SublimeJSCSFormatter#42]
I have a **.jscsrc** file on my project root path, I installed the newest JSCS  globally, I am using the **jscs-formatter** plugin of sublime text 3, but the JSCS just can't skip the **exculdeFiles** each time I press ctrl + s key to save file , any other rule works well. Here is my config detail.
{
  "preset":"airbnb",
  "fileExtensions": [".js", ".jsx"],
  "fix": true,
  "requireSemicolons": null,
  "disallowMultipleSpaces": true,
  "disallowSemicolons": true,
  "disallowSpaceBeforeComma": {"allExcept": ["sparseArrays"]},
  "excludeFiles": ["dist/****_",  "coverage/**_**"] 
}

**Comment by elicwhite** [comment]
Hmm. 

When you run jscs on explicitly that file from the command line, does it fix it even if it is in the excludeFiles?

If so, this sounds like a JSCS bug. JSCS-Formatter just simply calls JSCS to fix the currently opened file. It sounds like for this to work, you want JSCS when given a specific file and the --fix flag to not fix the file if it is in the ignored things in excludeFiles

**Comment by Kuznetsov2100** [comment]
The JSCS CLI works well to exclude files what I confiured in the .jscsrc file , I think It is the jscs-formatter's bug.

**Comment by elicwhite** [comment]
Does this occur when you manually call the formatter? As in, not using the format on save feature?

**Comment by Kuznetsov2100** [comment]
Yes!

**Comment by mrjoelkemp** [comment]
Hey @handane123, can you supply the console output from Sublime text: `View -> Show Console` after you run jscs-formatter?

**Comment by Kuznetsov2100** [comment]
Using node.js path on 'windows': node.exe
Using jscs path on 'windows': %APPDATA%/npm/node_modules/jscs/bin/jscs

**Comment by Kuznetsov2100** [comment]
I just found that  jscs just can be used on the project root path to function properly,if used in subdirectory, then jscs can't recognize the excludeFiles rule. So my suggestion is that jscs-formatter should call jscs on the project root path.

**Comment by elicwhite** [comment]
JSCS should probably work relative to the config file it finds instead of the formatter using a different CWD. @mrjoelkemp, do you agree?

**Comment by Kuznetsov2100** [comment]
It took me two hours to figure out! The problem is that you pass the string data to jscs,it looks like
![default](https://cloud.githubusercontent.com/assets/7983700/16022161/10c30880-31e9-11e6-91ae-2205facad53e.PNG)

**Comment by Kuznetsov2100** [comment]
So the jscs just ignored the config rules.
I make some little changes of  the **JSCS-Formatter.py**
- line 80: cdir = os.path.dirname(self.view.window().project_file_name())
- add one line code below line 80: cmd.append(self.view.file_name())
- line 158: stdout, stderr = p.communicate(input=None)
- remove the no used argument **data** of the function get_output()

**Comment by Kuznetsov2100** [comment]
I tried jscs in the subdirectories which I excluded in the .jscsrc file , it  now skips the file what I want.
And when used  upon the the normal file , it also works well to format code.
**Everything is done!**

**Comment by elicwhite** [comment]
Yeah, I'm not sure how we want to go about this. If we pass the file, we will be unable to format only the selected text. It would also cause JSCS to save the file which would cause sublime to reload it. I think that experience would be a little less than ideal. 

@handane123 Can you open a PR with your changes? It would be good to take a look and have them to consider.

**Comment by mrjoelkemp** [comment]
Thanks for investigating @handane123!  

Jscs is doing the right thing in my opinion; we pass a portion of a file and it doesn't know that the origin should have been excluded. 

Perhaps the plugin should prevent sending portions of an excluded file. Otherwise, jscs needs a special behavior when given piped text and a file argument.

**Comment by elicwhite** [comment]
I think this plugin trying to find and parse a configuration file is a recipe for pain and I know JSCS isn't adding new functionality since they are merging with eslint. I'm not sure there is a path forward here.

**Comment by mrjoelkemp** [comment]
Finding the jscsrc file is straightforward but parsing (non-json) configs would definitely be a headache.

Unfortunately, I also don't see a worthwhile path here. Sorry @handane123.
