### ISSUE TITLE
global name 'dirname' is not defined

### ISSUE THREAD

**Issue by varemenos** [TheSavior/SublimeJSCSFormatter#9]
For some reason this popup started showing and I can't get the formatter to work.
It was working just fine a few days ago when I first installed it. Also the `jscs ./ --fix` command works fine as well.

Here is the logged error from the Sublime console:

```
Using node.js path on 'linux': /home/adonisk/.nvm/v0.10.24/bin/node
Unexpected error(<class 'NameError'>): global name 'dirname' is not defined
error: global name 'dirname' is not defined
Traceback (most recent call last):
  File "/opt/sublime_text_3/sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "/home/adonisk/.config/sublime-text-3/Packages/SublimeJSCSFormatter/JSCSFormatter.py", line 42, in run
    if len(output) < 1:
TypeError: object of type 'NoneType' has no len()
```

**Comment by elicwhite** [comment]
Thanks for reporting this!

I'm not super sure why this is happening but I have my best case guess. 

I don't have linux and this doesn't repro on my machine, so hopefully you can help me out a little bit to debug this.
Can you open the file: `/home/adonisk/.config/sublime-text-3/Packages/SublimeJSCSFormatter/JSCSFormatter.py`

And change the contents of line 42 from `if output == None or len(output) < 1:` and replace it with `if output is None or len(output) < 1:`

I am wondering if the == check isn't catching it and so it tries to do `len(None)` which is causing what I believe is your real error:  `TypeError: object of type 'NoneType' has no len()`

You should be able to just save this file and re run the formatter. You may possibly need to restart sublime.

**Comment by varemenos** [comment]
It seems like I have the old version built before you had released it on package control so this issue should be considered invalid
